version: '3.4'
services:
  kafka:
    image: lensesio/fast-data-dev:latest
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    environment:
      ADV_HOST: localhost
      SAMPLEDATA: 0
      RUNNING_SAMPLEDATA: 0
      RUNTESTS: 0
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - 7050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  fss:
    build:
      context: .
      dockerfile: Dockerfile-compose
      network: host
      args:
        APPNAMEPATH: btn-chat-fss
    ports:
      - 7075:7075
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  sbs:
    build:
      context: .
      dockerfile: Dockerfile-compose
      network: host
      args:
        APPNAMEPATH: btn-chat-sbs
    ports:
      - 7076:7076
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
